### ISSUE TITLE
Add config reader

### ISSUE THREAD

**Issue by daniel-v** [daniel-v/dart_sass_builder#5]
Sass builder should be configurable via a config file.

In the config file, one is to be able to

- [ ] provide file globs to execute on
- [ ] provide compilation strategy (currently `dart` and `binary`)
- [ ] optionally provide extra arguments for binary compilation strategy

### Example 1:

```yaml
sass:
  builder: dart
files:
- web/*.scss
```

### Example 2:

```yaml
sass:
  builder: binary
  arguments:
  - node-sass
  - someotherarg
files:
- web/*.scss
```

#4 depends on this.
